### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by Miraitwo** [Xxiaoshan/MAC_UAMR#1]
Hello author,I am very interested in your project， I encountered an error while running your code
Traceback (most recent call last):
  File "H:\desktop\MAC_UAMR-main\Pretraing_MAC.PY", line 427, in <module>
    main()
  File "H:\desktop\MAC_UAMR-main\Pretraing_MAC.PY", line 351, in main
    train_loader, test_loader, n_data, index = load_RML2016(args)
  File "H:\desktop\MAC_UAMR-main\util.py", line 40, in load_RML2016
    IQ_train = load_pickle(filename_train_sne)
  File "H:\desktop\MAC_UAMR-main\util.py", line 14, in load_pickle
    f = open(file_name, "rb+")
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\pyALL\\调制识别数据集\\RML201610a_new\\py\\6_train_MV_dataset'
Your code is missing the code for dataset partitioning. If possible, could you please provide it? Looking forward to your reply

**Comment by Huo-yang** [comment]
I encountered the same problem, has it been solved?

**Comment by Miraitwo** [comment]
并没有解决，输入的数据集应该是处理过，看模型输入的格式是转换成了其他格式了> I encountered the same problem, has it been solved?
